# Generated by Django 6.1 on 2026-08-26 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('classes', models.CharField(help_text='কমা দিয়ে আলাদা করে ক্লাস/সেমিস্টার লিখুন, যেমন: শিশু,1,2,3,4,5', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(blank=True, choices=[('SCI', 'Science'), ('BUS', 'Business Studies'), ('HUM', 'Humanities'), ('DCS', 'Diploma in Computer Science'), ('DEL', 'Diploma in Electrical'), ('DCV', 'Diploma in Civil'), ('GEN', 'General'), ('NON', 'Non-Group')], max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.institution'),
        ),
    ]
