# Generated by Django 6.1 on 2026-08-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_admission_year_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='classes',
            field=models.CharField(help_text='Enter classes/semesters separated by commas, e.g.: Shishu,1,2,3,4,5', max_length=300),
        ),
    ]
