# Generated by Django 6.1 on 2026-08-26 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_institution_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=15),
        ),
        migrations.CreateModel(
            name='TransferCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('issued_by', models.CharField(blank=True, max_length=100)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_certificate', to='students.student')),
            ],
        ),
    ]
