# Generated by Django 6.1 on 2026-08-26 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_status_transfercertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('CHARACTER', 'Character Certificate'), ('STUDY', 'Study Certificate'), ('BONAFIDE', 'Bonafide Certificate')], max_length=15)),
                ('certificate_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('issued_by', models.CharField(blank=True, max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student')),
            ],
        ),
    ]
