# Generated by Django 6.1 on 2026-08-26 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSCRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=30, unique=True)),
                ('roll_number', models.CharField(blank=True, max_length=20)),
                ('session', models.CharField(help_text='e.g. 2025-2026', max_length=20)),
                ('group', models.CharField(choices=[('SCIENCE', 'Science'), ('COMMERCE', 'Business Studies'), ('ARTS', 'Humanities')], max_length=10)),
                ('subjects', models.CharField(blank=True, help_text='Comma-separated subject names', max_length=400)),
                ('board', models.CharField(choices=[('DHAKA', 'Dhaka Board'), ('CHATTOGRAM', 'Chattogram Board'), ('MADRASAH', 'Madrasah Board'), ('TECHNICAL', 'Technical Board')], max_length=15)),
                ('center', models.CharField(blank=True, max_length=150)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssc_registration', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='BoardResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2)),
                ('result_status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=4)),
                ('subject_wise_grades', models.TextField(blank=True, help_text='e.g. Bangla: A+, English: A')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('ssc_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board_result', to='students.sscregistration')),
            ],
        ),
    ]
