# Generated by Django 6.1 on 2026-08-26 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_sscregistration_boardresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('MID_TERM', 'Mid Term'), ('TERM_FINAL', 'Term Final'), ('OTHER', 'Other')], max_length=15)),
                ('admission_class', models.CharField(max_length=10)),
                ('section', models.CharField(blank=True, help_text='Leave blank to include all sections', max_length=5)),
                ('session', models.CharField(help_text='e.g. 2025-2026', max_length=20)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exam', 'student', 'subject'), name='unique_exam_student_subject')],
            },
        ),
    ]
