# Generated by Django 6.1 on 2026-08-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_exam_exammark'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor')], default='INDOOR', max_length=10)),
                ('seat_no', models.PositiveIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_plans', to='students.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['room_name', 'seat_no'],
                'constraints': [models.UniqueConstraint(fields=('exam', 'student'), name='unique_exam_seat_student'), models.UniqueConstraint(fields=('exam', 'room_name', 'seat_no'), name='unique_exam_room_seat')],
            },
        ),
    ]
