# Generated by Django 6.1 on 2026-08-27 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_employee_employeestatuslog_moneyreceipt_voucher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('applicant_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('applicant_contact_no', models.CharField(max_length=20)),
                ('applicant_address', models.TextField(blank=True)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_relation', models.CharField(blank=True, max_length=50)),
                ('guardian_contact_no', models.CharField(max_length=20)),
                ('guardian_address', models.TextField(blank=True)),
                ('requested_class', models.CharField(max_length=10)),
                ('requested_section', models.CharField(blank=True, max_length=5)),
                ('session', models.CharField(help_text='e.g. 2026-2027', max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('OFFICE_APPROVED', 'Office approved'), ('ACCOUNT_PENDING', 'Accounts pending'), ('PAYMENT_APPROVED', 'Payment approved'), ('REJECTED', 'Rejected'), ('ENROLLED', 'Enrolled')], default='SUBMITTED', max_length=20)),
                ('office_action_at', models.DateTimeField(blank=True, null=True)),
                ('office_remarks', models.TextField(blank=True)),
                ('account_action_at', models.DateTimeField(blank=True, null=True)),
                ('account_remarks', models.TextField(blank=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_purpose', models.CharField(default='Admission Fee', max_length=100)),
                ('next_step', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('account_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_admission_applications', to=settings.AUTH_USER_MODEL)),
                ('enrolled_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_application', to='students.student')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='students.institution')),
                ('office_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_admission_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
