# Generated by Django 6.1 on 2026-08-29 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_subject_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_class', models.CharField(help_text='e.g. 9, 10, 11, 12', max_length=10)),
                ('group', models.CharField(blank=True, choices=[('SCI', 'Science'), ('BUS', 'Business Studies'), ('HUM', 'Humanities'), ('DCS', 'Diploma in Computer Science'), ('DEL', 'Diploma in Electrical'), ('DCV', 'Diploma in Civil'), ('GEN', 'General'), ('NON', 'Non-Group')], help_text='Leave blank if this subject applies regardless of group.', max_length=3)),
                ('requirement_type', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('OPTIONAL', 'Optional (student chooses one from the same set)'), ('CONDITIONAL', 'Conditional (auto-added when condition matches)')], default='MANDATORY', max_length=12)),
                ('optional_set_key', models.CharField(blank=True, max_length=50)),
                ('condition_religion', models.CharField(blank=True, max_length=50)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_requirements', to='students.institution')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='students.subject')),
            ],
            options={
                'ordering': ['institution', 'admission_class', 'group', 'requirement_type', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_choices', to='students.student')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_by', to='students.subjectrequirement')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subjectrequirement',
            constraint=models.UniqueConstraint(fields=('institution', 'admission_class', 'group', 'subject'), name='unique_subject_requirement_per_class_group'),
        ),
        migrations.AddConstraint(
            model_name='studentsubjectchoice',
            constraint=models.UniqueConstraint(fields=('student', 'requirement'), name='unique_student_subject_choice'),
        ),
    ]
