# Generated by Django 6.1 on 2026-08-30 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_subjectrequirement_studentsubjectchoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Office', 'Office'), ('Exam', 'Exam'), ('Accounts', 'Accounts')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_accesses', to='students.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['institution__name', 'department'],
                'unique_together': {('user', 'institution', 'department')},
            },
        ),
    ]
