# Generated by Django 6.1 on 2026-08-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_admissionapplication_requested_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='student',
            name='discontinued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='discontinued_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('COMPULSORY', 'Compulsory Group'), ('OPTIONAL', 'Optional Group'), ('FOURTH', '4th Subject'), ('VOCATIONAL', 'Vocational'), ('RELIGION', 'Religion & Moral Education'), ('OTHER', 'Other')], default='OTHER', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=15),
        ),
    ]
