# Generated by Django 6.1 on 2026-08-31 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_subject_options_student_discontinued_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_class', models.CharField(max_length=10)),
                ('section', models.CharField(blank=True, max_length=5)),
                ('capacity', models.PositiveIntegerField(default=45)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_capacities', to='students.institution')),
            ],
            options={
                'ordering': ['institution', 'admission_class', 'section'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'admission_class', 'section'), name='unique_section_capacity')],
            },
        ),
    ]
