# Generated by Django 6.1 on 2026-08-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_sectioncapacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpromotionhistory',
            name='source_roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
