# Generated by Django 6.1 on 2026-09-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_student_pre_archive_status_student_restored_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('FIRST_TERM', 'First Term'), ('SECOND_TERM', 'Second Term'), ('THIRD_TERM', 'Third Term'), ('PRE_TEST_EXAM', 'Pre Test Exam'), ('TEST_EXAM', 'Test Exam'), ('MODEL_TEST_1', 'Model Test-1'), ('MODEL_TEST_2', 'Model Test-2'), ('MODEL_TEST_3', 'Model Test-3'), ('FINAL_TERM', 'Final Term'), ('MID_TERM_1', 'Mid Term-1'), ('MID_TERM_2', 'Mid Term-2'), ('MID_TERM_3', 'Mid Term-3')], max_length=15),
        ),
    ]
