# Generated by Django 6.1 on 2026-09-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cq_marks',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank if this subject has no CQ/MCQ split', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='mcq_marks',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank if this subject has no CQ/MCQ split', null=True),
        ),
    ]
