# Generated by Django 6.1 on 2026-09-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_subject_cq_marks_subject_mcq_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammark',
            name='cq_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exammark',
            name='mcq_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
