# Generated by Django 6.1 on 2026-09-05 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_exammark_cq_obtained_exammark_mcq_obtained'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMarkSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_class', models.CharField(help_text='e.g. 6, 9, 10', max_length=10)),
                ('exam_type', models.CharField(choices=[('FIRST_TERM', 'First Term'), ('SECOND_TERM', 'Second Term'), ('THIRD_TERM', 'Third Term'), ('PRE_TEST_EXAM', 'Pre Test Exam'), ('TEST_EXAM', 'Test Exam'), ('MODEL_TEST_1', 'Model Test-1'), ('MODEL_TEST_2', 'Model Test-2'), ('MODEL_TEST_3', 'Model Test-3'), ('FINAL_TERM', 'Final Term'), ('MID_TERM_1', 'Mid Term-1'), ('MID_TERM_2', 'Mid Term-2'), ('MID_TERM_3', 'Mid Term-3')], max_length=15)),
                ('full_marks', models.PositiveIntegerField(default=100)),
                ('cq_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('mcq_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_settings', to='students.institution')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_settings', to='students.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institution', 'admission_class', 'subject', 'exam_type'), name='unique_institution_class_subject_examtype')],
            },
        ),
    ]
