# Generated by Django 6.1 on 2026-09-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_subjectmarksetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='group',
            field=models.CharField(blank=True, choices=[('SCI', 'Science'), ('BUS', 'Business Studies'), ('HUM', 'Humanities'), ('DCS', 'Diploma in Computer Science'), ('DEL', 'Diploma in Electrical'), ('DCV', 'Diploma in Civil'), ('GEN', 'General'), ('NON', 'Non-Group')], max_length=5),
        ),
    ]
