# Generated by Django 5.2.17 on 2026-09-06 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_exam_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammark',
            name='practical_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exammark',
            name='weekly_test_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=40, help_text='Pass mark as a percentage of Full Marks. SSC rule is 40.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_marks',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank if this subject has no practical exam (e.g. Physics: 75 theory + 25 practical)', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='require_all_parts_pass',
            field=models.BooleanField(default=False, help_text='Failing any single part (CQ, MCQ, Practical, Weekly Test) fails the whole subject.'),
        ),
        migrations.AddField(
            model_name='subjectmarksetting',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=40, help_text='Pass mark as a percentage of Full Marks. SSC rule is 40.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='subjectmarksetting',
            name='practical_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectmarksetting',
            name='require_all_parts_pass',
            field=models.BooleanField(default=False, help_text='Failing any single part (CQ, MCQ, Practical, Weekly Test) fails the whole subject.'),
        ),
        migrations.AddField(
            model_name='subjectmarksetting',
            name='weekly_test_marks',
            field=models.PositiveIntegerField(blank=True, help_text='Only used for exam types that carry a weekly test (e.g. Mid Term).', null=True),
        ),
    ]
