# Generated by Arena Agent on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_clear_groups_below_class_9'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmarksetting',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Only checked subjects are offered for marks entry and counted in results for this exam type.',
            ),
        ),
    ]
