# Generated by Django 5.2.17 on 2026-09-09 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_remove_ssc_registration_and_board_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='students.institution'),
        ),
    ]
