# Generated by Django 5.2.17 on 2026-09-09 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0036_voucher_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionbatch',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_batches', to='students.institution'),
        ),
    ]
