# Generated by Django 5.2.17 on 2026-09-09 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0037_promotionbatch_institution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_class', models.CharField(max_length=10)),
                ('purpose', models.CharField(default='Admission Fee', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_created', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.institution')),
            ],
            options={
                'ordering': ['institution', 'admission_class', 'purpose'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'admission_class', 'purpose'), name='unique_fee_institution_class_purpose')],
            },
        ),
    ]
