# Generated by Django 5.2.17 on 2026-09-17 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0042_higher_math_mandatory_science'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='students.institution'),
        ),
    ]
