# Generated by Django 5.2.17 on 2026-09-20 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_auditlog_institution'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subjectmarksetting',
            name='unique_institution_class_subject_examtype',
        ),
        migrations.AddField(
            model_name='subjectmarksetting',
            name='group',
            field=models.CharField(blank=True, choices=[('SCI', 'Science'), ('BUS', 'Business Studies'), ('HUM', 'Humanities'), ('DCS', 'Diploma in Computer Science'), ('DEL', 'Diploma in Electrical'), ('DCV', 'Diploma in Civil'), ('GEN', 'General'), ('NON', 'Non-Group')], default='', help_text='Leave blank for the default that applies to every group; pick a group (e.g. Science) for a group-specific override. Groups only apply to classes 9-12.', max_length=3),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=40, help_text='Pass mark as a percentage of Full Marks. SSC rule is 40.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='subjectmarksetting',
            name='full_marks',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subjectmarksetting',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=40, help_text='Pass mark as a percentage of Full Marks. SSC rule is 40.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='subjectmarksetting',
            constraint=models.UniqueConstraint(fields=('institution', 'admission_class', 'subject', 'exam_type', 'group'), name='unique_institution_class_subject_examtype_group'),
        ),
    ]
