# Generated by Django 6.1 on 2026-09-21 03:56

import students.models
from django.conf import settings
from django.db import migrations, models


def create_default_row(apps, schema_editor):
    """Create the single branding row so it can be edited in the admin."""
    SiteBranding = apps.get_model('students', 'SiteBranding')
    SiteBranding.objects.get_or_create(
        pk=1,
        defaults={
            'developer_name': settings.DEVELOPER_NAME,
            'copyright_holder': settings.COPYRIGHT_HOLDER,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_auditlog_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(default=students.models.default_developer_name, max_length=100)),
                ('copyright_holder', models.CharField(default=students.models.default_copyright_holder, max_length=100)),
            ],
            options={
                'verbose_name': 'Site branding',
                'verbose_name_plural': 'Site branding',
            },
        ),
        migrations.RunPython(create_default_row, migrations.RunPython.noop),
    ]
