# Generated by Django 6.1 on 2026-09-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0044_remove_subjectmarksetting_unique_institution_class_subject_examtype_and_more'),
        ('students', '0044_site_branding'),
    ]

    operations = [
    ]
