# Generated by Django 6.1 on 2026-09-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0045_merge_20260921_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitCacheEntry',
            fields=[
                ('cache_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('expires', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'django_cache',
                'default_permissions': (),
            },
        ),
    ]
