# Generated by Django 5.2.17 on 2026-10-07 04:36

import students.photo_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0046_rate_limit_cache_table'),
    ]

    operations = [
        # upload_to, help_text, and validators do not change the database
        # column. Keep Django's migration state aligned without rebuilding the
        # Student table on SQLite or issuing a no-op ALTER in production.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='student',
                    name='photo',
                    field=models.ImageField(
                        blank=True,
                        help_text='JPG, PNG or GIF; 2 MiB max; dimensions 300×300 to 4096×4096 px.',
                        null=True,
                        upload_to=students.photo_uploads.student_photo_upload_to,
                        validators=[students.photo_uploads.validate_student_photo],
                    ),
                ),
            ],
        ),
    ]
