# Generated by Django 5.2.17 on 2026-10-07 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0047_alter_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPhotoDeletionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_alias', models.CharField(default='default', max_length=100)),
                ('name', models.CharField(max_length=512)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_type', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['next_attempt_at', 'pk'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['next_attempt_at', 'id'], name='student_photo_del_due')],
            },
        ),
    ]
